### ISSUE TITLE
Embed regional inventories

### ISSUE THREAD

**Issue by rt17603** [ACRG-Bristol/acrg#102]
**[Original report](https://bitbucket.org/mrghg/acrg/issue/94) by Hannah Chawner (Bitbucket: [Hannah Chawner](https://bitbucket.org/Hannah Chawner), GitHub: [hanchawn](https://github.com/hanchawn)).**

----------------------------------------

Adapt the emissions\_helperfuncs.embed\_UKGHG\_EDGAR function to allow for embedding any regional inventory into another using a country mask, to create a combined flux map

**Comment by hanchawn** [comment]
Resolved by PR #5
