### ISSUE TITLE
test needed for fill_gaps in create_country_mask_eez

### ISSUE THREAD

**Issue by rt17603** [ACRG-Bristol/acrg#125]
**[Original report](https://bitbucket.org/mrghg/acrg/issue/117) by Alice Ramsden (Bitbucket: [aeramsden](https://bitbucket.org/aeramsden), GitHub: [aliceramsden](https://github.com/aliceramsden)).**

----------------------------------------

The ‘fill\_gaps’ section in countrymask.create\_country\_mask\_eez fills in gaps between the ocean and land countrymasks by filling any cells where all surrounding cells have the same value. I have tested this manually but there is no written test for this.

Currently, a warning is printed out, letting users know that this part of the function is untested.

**Comment by aliceramsden** [comment]
Solved by pull request #7.
