### ISSUE TITLE
test_get_country fails with a clean repository

### ISSUE THREAD

**Issue by angharadstell** [ACRG-Bristol/acrg#133]
I've just run the tests on a clean repository, and test_get_country fails. This is because there is no folder "tests/files/LPDM/countries". I made the countries folder and reran the tests and now it works.

Seems like a pretty easy fix but I don't know if you'd rather fix this differently!

**Comment by joe-pitt** [comment]
This should now be fixed - I added a dummy .gitkeep file to the directory tests/files/LPDM/countries because empty directories don't get committed.
