### ISSUE TITLE
Upgrade pinned packages in acrg_environment.yml

### ISSUE THREAD

**Issue by rt17603** [ACRG-Bristol/acrg#86]
**[Original report](https://bitbucket.org/mrghg/acrg/issue/78) by Rachel Tunnicliffe (Bitbucket: [rt17603](https://bitbucket.org/rt17603), GitHub: [rt17603](https://github.com/rt17603)).**

----------------------------------------

Package versions within the acrg\_environment.yml file are currently pinned and will need to be upgraded to later versions, ensuring that the tests can still pass before updating.

**Comment by mrghg** [comment]
Resolved in PR #6
